import { ProductCard } from "@/components/storefront/ProductCard";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ArrowUpRight, HeartHandshake } from "lucide-react";
import { Link } from "wouter";

export default function Home() {
  const { data: products = [], isLoading, isError } = trpc.commerce.products.list.useQuery({ first: 4 });

  return (
    <main>
      <section className="ets-hero px-5 pb-16 pt-20 text-white sm:px-8 sm:pb-24 sm:pt-28 lg:px-12 lg:pb-28 lg:pt-36">
        <div className="mx-auto max-w-[1280px]">
          <p className="eyebrow hero-eyebrow">Merchandising solidale / A-Tono ETS</p>
          <div className="mt-9 max-w-[890px]"><h1 className="font-display text-[4.15rem] font-light leading-[0.82] tracking-[-0.055em] sm:text-[6.8rem] lg:text-[8.75rem]">Un gesto<br /><span className="text-white/45">che resta.</span></h1></div>
          <div className="mt-12 grid max-w-[870px] gap-7 border-l-2 border-[#9fc0dc] pl-6 sm:mt-16 sm:grid-cols-[1.2fr_.8fr] sm:pl-8"><p className="text-xl font-light leading-8 text-[#e7f1f8] sm:text-2xl sm:leading-9">Oggetti essenziali, scelti per raccontare un impegno concreto verso le persone e i territori.</p><div className="flex items-end"><Link href="/shop" className="action-pill">Esplora lo shop <ArrowRight size={17} aria-hidden="true" /></Link></div></div>
        </div>
      </section>

      <section className="px-5 py-18 sm:px-8 sm:py-24 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="eyebrow">Il significato dell’acquisto</p><div className="section-rule mt-5" /><h2 className="section-title mt-8 text-5xl sm:text-6xl">Non solo<br /><strong className="font-bold text-[#7a9cbf]">merchandising.</strong></h2></div><div className="max-w-[660px] self-end"><p className="text-lg font-light leading-8 text-[#51687e]">Lo shop di A-Tono ETS è un modo in più per scegliere di esserci. Ogni acquisto contribuisce a sostenere progetti e iniziative che mettono in relazione bisogni sociali reali, competenze e comunità.</p><a href="https://ets.a-tono.com/progetti.html" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#456987] transition-colors hover:text-[#7a9cbf]">Scopri le realtà sostenute <ArrowUpRight size={15} aria-hidden="true" /></a></div></div></section>

      <section className="bg-[#edf4f8] px-5 py-18 sm:px-8 sm:py-24 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div><p className="eyebrow">Edizione ETS</p><h2 className="section-title mt-5 text-5xl sm:text-6xl">Scegli ciò che<br /><strong className="font-bold text-[#7a9cbf]">ti accompagna.</strong></h2></div><Link href="/shop" className="back-link">Vedi tutto lo shop <ArrowRight size={14} aria-hidden="true" /></Link></div><div className="mt-12 grid gap-9 sm:grid-cols-2">{isLoading ? [0, 1].map(item => <div key={item} className="animate-pulse"><div className="aspect-[1/1.1] bg-[#dce8f0]" /><div className="mt-5 h-3 w-28 bg-[#cfdee8]" /><div className="mt-3 h-8 w-4/5 bg-[#cfdee8]" /><div className="mt-5 h-3 w-full bg-[#d7e4ec]" /></div>) : isError ? <div className="col-span-full rounded-sm border border-[#cbd8e2] bg-white px-7 py-12 text-center"><p className="font-display text-3xl font-light text-[#2b3e52]">Lo shop non è disponibile in questo momento.</p><Link href="/shop" className="action-pill mt-6">Riprova</Link></div> : products.length ? products.map(product => <ProductCard key={product.id} product={product} compact />) : <div className="col-span-full rounded-sm border border-dashed border-[#b9c9d6] bg-white px-7 py-12 text-center"><p className="font-display text-3xl font-light text-[#2b3e52]">Stiamo preparando i primi oggetti.</p></div>}</div></div></section>

      <section id="impatto" className="px-5 py-18 sm:px-8 sm:py-24 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="grid gap-10 lg:grid-cols-[.76fr_1.24fr] lg:gap-20"><div><p className="eyebrow">A-Tono ETS</p><h2 className="section-title mt-5 text-5xl sm:text-6xl">Un acquisto.<br /><strong className="font-bold text-[#7a9cbf]">Una relazione.</strong></h2></div><div className="max-w-[670px] self-end"><p className="text-lg font-light leading-8 text-[#51687e]">La nostra azione coniuga visione strategica, supporto operativo e cura delle relazioni. Il merchandising solidale è un gesto di vicinanza al percorso dell’ETS e alle realtà che incontra.</p></div></div><div className="mt-12 grid gap-px overflow-hidden bg-white sm:grid-cols-3"><article className="relative min-h-[340px] overflow-hidden bg-[#2b3e52]"><img src="/manus-storage/progetto-20_92d842bb.jpg" alt="Progetto Partizan" className="h-full w-full object-cover opacity-65 mix-blend-luminosity" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#1f3446] via-[#1f3446]/75 to-transparent p-6 pt-20 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#b8d4ea]">Comunità e sport</p><h3 className="mt-2 font-display text-3xl font-light">Partizan</h3></div></article><article className="relative min-h-[340px] overflow-hidden bg-[#486983]"><img src="/manus-storage/progetto-17_ad304b14.jpg" alt="Progetto Cabina Rosa" className="h-full w-full object-cover opacity-65 mix-blend-luminosity" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#1f3446] via-[#1f3446]/75 to-transparent p-6 pt-20 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#b8d4ea]">Impegno sociale</p><h3 className="mt-2 font-display text-3xl font-light">Cabina Rosa</h3></div></article><article className="relative min-h-[340px] overflow-hidden bg-[#7a9cbf]"><img src="/manus-storage/progetto-6_a0e80871.jpg" alt="Progetto ANDOS" className="h-full w-full object-cover opacity-65 mix-blend-luminosity" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#1f3446] via-[#1f3446]/75 to-transparent p-6 pt-20 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#b8d4ea]">Prevenzione</p><h3 className="mt-2 font-display text-3xl font-light">ANDOS</h3></div></article></div><div className="mt-8 flex flex-col justify-between gap-5 border-t border-[#cbd8e2] pt-7 sm:flex-row sm:items-center"><p className="flex items-center gap-3 text-sm font-light text-[#51687e]"><HeartHandshake className="text-[#7a9cbf]" size={21} aria-hidden="true" /> Conosci il lavoro dell’ETS e le realtà incontrate nel tempo.</p><a href="https://ets.a-tono.com/progetti.html" target="_blank" rel="noreferrer" className="action-pill action-pill-outline w-fit">Tutti i progetti <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></section>

      <section className="bg-[linear-gradient(120deg,#2b3e52,#5b7999)] px-5 py-18 text-white sm:px-8 sm:py-24 lg:px-12 lg:py-28"><div className="mx-auto max-w-[980px] text-center"><p className="eyebrow text-[#c2dbed]">Sostieni A-Tono ETS</p><h2 className="mt-6 font-display text-5xl font-light leading-[.95] tracking-[-.045em] sm:text-7xl">Il cambiamento si fa<br /><span className="text-white/48">insieme.</span></h2><p className="mx-auto mt-8 max-w-[560px] text-lg font-light leading-8 text-[#ecf5fb]">Porta con te un gesto di partecipazione e scopri come sostenere le iniziative dell’associazione.</p><Link href="/shop" className="action-pill mt-10 bg-white text-[#2b3e52] hover:bg-[#dceaf4] hover:text-[#2b3e52]">Vai allo shop <ArrowRight size={17} aria-hidden="true" /></Link></div></section>
    </main>
  );
}
